### ISSUE TITLE
async getLocation() only returns first element

### ISSUE THREAD

**Issue by que232** [loloToster/openweather-api-node#3]
**Describe the bug**
If more than one city exists with the same name, getLocation() only returns the first element. (limet=1 in geocodeing request).
That makes it impossible to get geocoding for a city such as Wausau, FL, or Nome, TX.
**To Reproduce**
{location = await weather.getLocation({locationName: city})	
		console.log ("LOCATION: ",location);
}
**Expected behavior**
Should be able to put "city,state" in the weather.getLocation call.
**Screenshots**
**Please complete the following information:**
Node version: 16.13.2
openweather-api-node version: 1.3.2

**Additional context**.
Since Openweathermaps will be depricating getting weather by city, this will become a bigger issue in the future.

**Comment by que232** [comment]
Sending city,state,us works, but not ideal since many countries don't have states. 
So, this isn't really a bug, but a feature request. The problem is in the API.
I'll try to figure out how to determine if the request is "city,state" or "city,country".

**Comment by loloToster** [comment]
As you said this is more of an API problem but after reading your issue I noticed that there is no method to get more then one location from query so I added one called `getAllLocations`. Thanks for your input. :)
