### ISSUE TITLE
`FREE` accounts can't use all the available methods for that account type

### ISSUE THREAD

**Issue by IvanGodinez21** [loloToster/openweather-api-node#5]
**Describe the bug**
Can't use this library to interact with the API using `FREE` plan.

**To Reproduce**
1. Copy one of the examples of the `README.md`.
2. Run it.
3. See error.

**Expected behavior**
Be able to get information using the methods.

**Screenshots**
*None*

**Please complete the following information:**
Node version: 16.19.0
openweather-api-node version: 2.0.0

**Additional context**
I think the problem is that `FREE` accounts can't use the `onecall` route, which is used in several methods. Example:
```
    async getCurrent(options = {}) {
        await this.uncacheLocation();
        const parsedOptions = await this.parseOptions(options);
        let response = await this.fetch(this.createURL(parsedOptions, constants_1.ONECALL_PATH, {
            exclude: "alerts,minutely,hourly,daily",
        }));
        let data = response.data;
        return (0, current_parser_1.default)(data);
    }
```
So, for example, when I access to the route in the web explorer it doesn't work (Change SECRET):
✖️ `https://api.openweathermap.org/data/2.5/onecall?appid=SECRET&lat=51.509865&lon=-0.118092`.
But using the example provided by OpenWeatherMap works:
✔️ `https://api.openweathermap.org/data/2.5/weather?appid=SECRET&lat=51.509865&lon=-0.118092`.

Maybe creating different constant paths and assigning it to the methods may solve this issue.

**Comment by loloToster** [comment]
This problem occurs due to new OneCall 3.0 api. For now the package will not work with newly created keys. I will get on fixing it as soon as I can.
Thanks for reporting the issue.

**Comment by loloToster** [comment]
The latest update should resolve the issue. The update also adds new `getForecast` method which allows to use `https://api.openweathermap.org/data/2.5/forecast` endpoint.
If the problem persists after updating the package please reopen the issue.
