### ISSUE TITLE
One Call API 3.0 Support

### ISSUE THREAD

**Issue by enchorb** [loloToster/openweather-api-node#6]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Are there any plans to support the 3.0 API soon? For the time being I used [patch-package](https://github.com/ds300/patch-package) to get it working

```diff
diff --git a/node_modules/openweather-api-node/dist/constants.js b/node_modules/openweather-api-node/dist/constants.js
index 045baa7..35f6651 100644
--- a/node_modules/openweather-api-node/dist/constants.js
+++ b/node_modules/openweather-api-node/dist/constants.js
@@ -55,7 +55,7 @@ exports.SUP_LANGS = [
 exports.SUP_UNITS = ["standard", "metric", "imperial"];
 exports.API_ENDPOINT = "https://api.openweathermap.org/";
 exports.GEO_PATH = "geo/1.0/";
-exports.DATA_PATH = "data/2.5";
+exports.DATA_PATH = "data/3.0";
 exports.WEATHER_PATH = exports.DATA_PATH + "/weather";
 exports.FORECAST_PATH = exports.DATA_PATH + "/forecast";
 exports.ONECALL_PATH = exports.DATA_PATH + "/onecall";
```

**Comment by loloToster** [comment]
Hello!
I'm planning on making version 3.0 of the package (which will have support for the 3.0 API). Currently I don't have enough time but I will start working on it in a couple of weeks.

**Comment by loloToster** [comment]
The `openweather-api-node@3.0.0` is out and it has support for version 3.0 of the onecall api.
